<?php require_once('Views/template/header.phtml'); ?>

<?php foreach ($view->deliveryPointDataSet as $deliveryPointData) : ?>
    <?php
    $editUrl = 'edit.php?id=' . $deliveryPointData->getDeliveryID();
    $deleteUrl = 'delete.php?id=' . $deliveryPointData->getDeliveryID();
    $parcelUrl = 'parcel.php?id=' . $deliveryPointData->getDeliveryID();
    ?>
    <div class="card mb-5">
        <div class="card-header d-flex">
            <div class="col-6 col-sm-8 col-md-10 col-lg-10">
                <h5 class="mb-0"><a href='<?= $parcelUrl ?>'> Parcel ID: <?= $deliveryPointData->getDeliveryID() ?></a></h5>
            </div>
            <div class="d-flex justify-content-end col-6 col-sm-4 col-md-2 col-lg-2">
                <div class="px-1">
                <a href="insert.php">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-file-earmark-plus" viewBox="0 0 16 16">
                        <path d="M8 6.5a.5.5 0 0 1 .5.5v1.5H10a.5.5 0 0 1 0 1H8.5V11a.5.5 0 0 1-1 0V9.5H6a.5.5 0 0 1 0-1h1.5V7a.5.5 0 0 1 .5-.5"/>
                        <path d="M14 4.5V14a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h5.5zm-3 0A1.5 1.5 0 0 1 9.5 3V1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V4.5z"/>
                    </svg>
                </a>
                </div>
                <div class="px-1">
                    <a href="<?= $editUrl ?>">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="green" class="bi bi-pencil-square" viewBox="0 0 16 16">
                        <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                        <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z"/>
                    </svg>
                    </a>
                </div>
                <div class="px-1">
                    <a href="<?= $deleteUrl ?>">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="red" class="bi bi-file-earmark-minus" viewBox="0 0 16 16">
                        <path d="M5.5 9a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1H6a.5.5 0 0 1-.5-.5"/>
                        <path d="M14 4.5V14a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h5.5zm-3 0A1.5 1.5 0 0 1 9.5 3V1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V4.5z"/>
                    </svg>
                    </a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6 col-md-6 col-lg-8">
                <div class="card-body">
                    <p class="mb-2"><strong>Name: </strong><?= $deliveryPointData->getName() ?></p>
                    <p class="mb-0"><strong>Address: </strong><?= $deliveryPointData->getAddress1() ?> - <?= $deliveryPointData->getPostcode() ?></p>
                    <p class="mb-2">(<i><?= $deliveryPointData->getLat(); ?></i>, <i><?= $deliveryPointData->getLong(); ?>)</i></p>
                    <p class="mb-2"><strong>Courier: </strong><?= $deliveryPointData->getDeliverer() ?></p>
                    <p class="mb-2"><strong>Status: </strong><?= $deliveryPointData->getStatus() ?></p>
                </div>
            </div>
            <div class=" col-sm-6 col-md-6 col-lg-4 d-flex align-items-center">
                <div class="card-body d-flex justify-content-center align-items-center">
                    <div class="qr-code" id="<?= $deliveryPointData->getDeliveryID() ?>"></div>
                </div>
            </div>
        </div>
    </div>
<?php endforeach; ?>

<nav aria-label="...">
    <ul class="pagination pagination-md justify-content-center">
        <li class="page-item <?= $view->pageNumber <= 1 ? 'disabled' : '' ?>">
            <a class="page-link" href="?page=<?= $view->pageNumber - 1 ?>" tabindex="-1">Previous</a>
        </li>
        <?php
        $startPage = max(1, $view->pageNumber - 2);
        $endPage = min($startPage + 4, $view->totalPages);

        for ($i = $startPage; $i <= $endPage; $i++) { ?>
            <li class="page-item <?= $view->pageNumber == $i ? 'active' : '' ?>">
                <a class="page-link" href="?page=<?= $i ?>"><?= $i ?></a>
            </li>
        <?php } ?>
        <li class="page-item <?= $view->pageNumber >= $view->totalPages ? 'disabled' : '' ?>">
            <a class="page-link" href="?page=<?= $view->pageNumber + 1 ?>">Next</a>
        </li>
    </ul>
</nav>

<?php require_once('Views/template/footer.phtml') ?>