<?php require_once('Views/template/header.phtml'); ?>

    <?php foreach ($view->deliveryPointDataSet as $deliveryPointData) : ?>
        <div class="card mb-5">
            <div class="card-header">
                <h5 class="mb-0"> Parcel ID: <?= $deliveryPointData->getDeliveryID() ?></h5>
            </div>
            <div class="row">
                <div class="col-sm-6 col-md-6 col-lg-8">
                    <div class="card-body">
                        <p class="card-text mb-2"><strong>Name: </strong><?= $deliveryPointData->getName() ?></p>
                        <p class="card-text mb-0"><strong>Address: </strong><?= $deliveryPointData->getAddress1() ?> - <?= $deliveryPointData->getPostcode() ?></p>
                        <p class="mb-2">(<i><?= $deliveryPointData->getLat(); ?></i>, <i><?= $deliveryPointData->getLong(); ?>)</i></p>
                        <select>
                                <?php foreach ($view->deliveryPointStatus as $status) : ?>
                            <option>
                            <?= $status['status_text'] ?>
                            <?php endforeach; ?>
                            </option>
                        </select>
                    </div>
                </div>
                <div class=" col-sm-6 col-md-6 col-lg-4 d-flex align-items-center">
                    <div class="card-body d-flex justify-content-center align-items-center">
                        <img style="width: 115px; height: 115px;" src="https://boofcv.org/images/thumb/3/35/Example_rendered_qrcode.png/400px-Example_rendered_qrcode.png">
                    </div>
                </div>
            </div>
        </div>
    <?php endforeach; ?>

<?php require_once('Views/template/footer.phtml') ?>