<?php require_once('Views/template/header.phtml'); ?>

    <?php foreach ($view->deliveryPointDataSet as $deliveryPointData) : ?>
        <div class="card mb-5">
            <div class="card-header">
                <h5 class="mb-0"> Parcel ID: <?= $deliveryPointData->getDeliveryID() ?></h5>
            </div>
            <div class="row">
                <div class="col-sm-6 col-md-6 col-lg-8">
                    <div class="card-body">
                        <p class="card-text mb-2"><strong>Name: </strong><?= $deliveryPointData->getName() ?></p>
                        <p class="card-text mb-0"><strong>Address: </strong><?= $deliveryPointData->getAddress1() ?> - <?= $deliveryPointData->getPostcode() ?></p>
                        <p class="mb-2">(<i><?= $deliveryPointData->getLat(); ?></i>, <i><?= $deliveryPointData->getLong(); ?>)</i></p>
                        <p class="mb-2"><strong>Courier: </strong><?= $deliveryPointData->getDeliverer() ?></p>
                        <p class="mb-2"><strong>Status: </strong><?= $deliveryPointData->getStatus() ?></p>
                    </div>
                </div>
                <div class=" col-sm-6 col-md-6 col-lg-4 d-flex align-items-center">
                    <div class="card-body d-flex justify-content-center align-items-center">
                        <div class="qr-code" id="<?= $deliveryPointData->getDeliveryID() ?>"></div>
                    </div>
                </div>
            </div>
        </div>
    <?php endforeach; ?>

<nav aria-label="...">
    <ul class="pagination pagination-md justify-content-center">
        <li class="page-item <?= $view->pageNumber <= 1 ? 'disabled' : '' ?>">
            <a class="page-link" href="?page=<?= $view->pageNumber - 1 ?>" tabindex="-1">Previous</a>
        </li>
        <?php
        $startPage = max(1, $view->pageNumber - 2);
        $endPage = min($startPage + 4, $view->totalPages);

        for ($i = $startPage; $i <= $endPage; $i++) { ?>
            <li class="page-item <?= $view->pageNumber == $i ? 'active' : '' ?>">
                <a class="page-link" href="?page=<?= $i ?>"><?= $i ?></a>
            </li>
        <?php } ?>
        <li class="page-item <?= $view->pageNumber >= $view->totalPages ? 'disabled' : '' ?>">
            <a class="page-link" href="?page=<?= $view->pageNumber + 1 ?>">Next</a>
        </li>
    </ul>
</nav>

<?php require_once('Views/template/footer.phtml') ?>