<?php require_once('Views/template/header.phtml'); ?>

<form method="post" action="<?= $_SERVER['PHP_SELF']; ?>">
    <!-- User Name Input -->
    <div class="form-group">
        <label for="username">User name</label>
        <input type="text" class="form-control" name="username" id="username">
    </div>

    <!-- Password Input -->
    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" name="password" id="password">
    </div>

    <!-- Submit Button -->
    <input type="submit" name="submit" value="Login" class="btn btn-primary">
</form>

<?php require_once('Views/template/footer.phtml'); ?>
