<!DOCTYPE html>
<html>
<head>
    <title>ParcelBuddy</title>
    <link rel="stylesheet" href="css/styles.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="index.php"><i>Parcel Buddy</i></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="delivery.php">Parcels</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="dashboard.php">Dashboard</a>
                </li>
            </ul>
            <form class="d-flex" action="" role="search">
            // Use action
            <form class="d-flex" action="<?php echo $_SERVER['PHP_SELF']; ?>" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" name="search" aria-label="Search">
                <button class="btn btn-outline-success me-2" name="searchBtn" type="submit">Search</button>
            </form>
            <form action="logout.php">
                <?php echo (isset($_SESSION['login'])) ? '<button class="btn btn-light" name="logout" type="submit">Logout</button>' : ''; ?>
            </form>
        </div>
    </div>
</nav>
<div id="container">
    <div id="title">
        <h2><?= $view->pageTitle; ?></h2>
    </div>